ezpublish:
    # Define all your repositories here
    # If you use multi-site with multiple databases, you should define multiple repositories
    repositories:
        # "main" repository, with default values for storage
        # Same as:
        # main:
        #     storage:
        #         engine: legacy
        #         connection: default
        #     search:
        #         engine: %search_engine%
        #         connection: default
        main:
            storage: ~
            search:
                engine: %search_engine%
                connection: default

    siteaccess:
        # Available siteaccesses
        list:
            - site
            - mobile
        # Siteaccess groups. Use them to group common settings.
        groups:
            site_group: [site]
        default_siteaccess: site
        match:
            URIElement: 1

    imagemagick:
        enabled: false

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            # The repository to use. Here "main", which is defined in "repositories" above.
            repository: main
            languages: [eng-GB]
            session:
                name: MyFrontendSessionName
        default:
            content:
                view_cache: true
                ttl_cache: true
                # TTL cache (http) in seconds
                # Note that Http cache for a given content is always invalidated when publishing that content
                default_ttl: 300
